
[studenten]
filter = "CN=MLU Student,OU=MLU Global,OU=Uni-Halle,DC=xd,DC=uni-halle,DC=de"
groupName = "studenten"

[mitarbeiter]
filter = "CN=MLU Mitarbeiter,OU=MLU Global,OU=Uni-Halle,DC=xd,DC=uni-halle,DC=de"
groupName = "mitarbeiter"

